---
- name: run checks to ensure gitea_oauth2_jwt_secret do not crash gitea and is idempotent
  block:
    - name: "check token length"
      fail:
        msg: 'gitea_oauth2_jwt_secret has to be 43 characters long.'
      when: gitea_oauth2_jwt_secret | length != 43

- name: run checks to ensure gitea_lfs_jwt_secret do not crash gitea and is idempotent
  block:
    - name: "check token length"
      fail:
        msg: 'gitea_lfs_jwt_secret has to be 43 characters long.'
      when: gitea_lfs_jwt_secret | length != 43
