---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: debian-stretch
    image: debian:stretch
  - name: debian-jessie
    image: debian:jessie
  - name: ubuntu-xenial
    image: ubuntu:xenial
  - name: ubuntu-bionic
    image: ubuntu:bionic
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - destroy

verifier:
  name: testinfra
  lint:
    name: flake8
